name: Test Python Application
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  test-python-application:
    runs-on: ubuntu-latest
    container:
      image: rbikai/python
      env:
        ENV_TO_REPLACE: ${{ github.head_ref || github.ref_name }}
      ports:
        - 80
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@v4
      - name: Test my python application
        run: pytest --cov=. mytest.py --json-report
      - name: Test my python application
        run: ls -ltr
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .report.json
          retention-days: 10
  push-docker-image:
    needs: test-python-application
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t rbikai/python:${{ github.head_ref || github.ref_name }} .
      - name: Push the image to dockerhub
        run: docker push rbikai/python:${{ github.head_ref || github.ref_name }}
