name: mainAction
on:
  push:
    branches:
    - main
jobs:
  test-python-application:
    runs-on: ubuntu-latest
    container:
      image: rbikai/python
      env:
        ENV_TO_REPLACE: ${{ github.head_ref || github.ref_name }}
      ports:
        - 80
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@v4
      - name: Test my python application
        run: pytest --cov=. mytest.py --json-report
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t rbikai/python:${{ github.head_ref || github.ref_name }} .
      - name: Push the image to dockerhub
        run: docker push rbikai/python:${{ github.head_ref || github.ref_name }}
